/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.controller.DemoController;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DemoController_SSTest extends DemoController_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      //caseID:a1da6de566d9343b63c478d3b626ea86
      DemoController demoController0 = new DemoController();
  }}
