/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.config.WebConfig;
import java.util.ArrayList;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.springframework.web.method.support.HandlerMethodArgumentResolver;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class WebConfig_SSTest extends WebConfig_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_addArgumentResolvers_0()  throws Throwable  {
      //caseID:e7f1ec4ab03a1450ab9b24195821a3a5
      WebConfig webConfig0 = new WebConfig();
      ArrayList<HandlerMethodArgumentResolver> arrayList0 = new ArrayList<HandlerMethodArgumentResolver>();
      webConfig0.addArgumentResolvers(arrayList0);
      assertEquals(1, arrayList0.size());
  }}
