/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.jesper.seckill.validator.IsMobile;
import com.jesper.seckill.validator.IsMobileValidator;
import javax.validation.ConstraintValidatorContext;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class IsMobileValidator_SSTest extends IsMobileValidator_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_isValid_0()  throws Throwable  {
      //caseID:c45ce22775ba75e5770bcff3247efcd1
      IsMobileValidator isMobileValidator0 = new IsMobileValidator();
      ConstraintValidatorContext constraintValidatorContext0 = mock(ConstraintValidatorContext.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      boolean boolean0 = isMobileValidator0.isValid("tzbAY'", constraintValidatorContext0);
      assertFalse(boolean0);
  }
  @Test(timeout = 4000)
  public void test_initialize_1()  throws Throwable  {
      //caseID:1b6dc8156b612f4f282acdd7b8fa64e5
      IsMobileValidator isMobileValidator0 = new IsMobileValidator();

      //prepare data for isMobile0
      IsMobile isMobile0 = mock(IsMobile.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(true).when(isMobile0).required();

      //invoke method for isMobileValidator0
      isMobileValidator0.initialize(isMobile0);
  }
  @Test(timeout = 4000)
  public void test_isValid_2()  throws Throwable  {
      //caseID:09723f3a6585c22edc33948917efd4cb
      IsMobileValidator isMobileValidator0 = new IsMobileValidator();
      ConstraintValidatorContext constraintValidatorContext0 = mock(ConstraintValidatorContext.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      boolean boolean0 = isMobileValidator0.isValid("1", constraintValidatorContext0);
      assertFalse(boolean0);
  }
  @Test(timeout = 4000)
  public void test_isValid_3()  throws Throwable  {
      //caseID:7dec130d9452ac508531582d0c0e1de6
      IsMobileValidator isMobileValidator0 = new IsMobileValidator();
      ConstraintValidatorContext constraintValidatorContext0 = mock(ConstraintValidatorContext.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      boolean boolean0 = isMobileValidator0.isValid("", constraintValidatorContext0);
      assertTrue(boolean0);
  }}
