/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.rabbitmq;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.rabbitmq.MQConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.springframework.amqp.core.Binding;
import org.springframework.amqp.core.Queue;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MQConfig_SSTest extends MQConfig_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_queue_0()  throws Throwable  {
      //caseID:a946e68c61eb8e5aacbebac39a6f4f87
      MQConfig mQConfig0 = new MQConfig();
      Queue queue0 = mQConfig0.queue();
      assertTrue(queue0.isDurable());
      assertEquals("queue", queue0.getName());
  }
  @Test(timeout = 4000)
  public void test_topicBinding2_1()  throws Throwable  {
      //caseID:3bc539c89ece9c9590ae46adfa7c9d5d
      MQConfig mQConfig0 = new MQConfig();
      Binding binding0 = mQConfig0.topicBinding2();
      assertEquals("topic.queue2", binding0.getDestination());
      assertEquals("topicExchage", binding0.getExchange());
      assertEquals("topic.#", binding0.getRoutingKey());
  }
  @Test(timeout = 4000)
  public void test_topicBinding1_2()  throws Throwable  {
      //caseID:34a7190d776c1cf082b082d477e35168
      MQConfig mQConfig0 = new MQConfig();
      Binding binding0 = mQConfig0.topicBinding1();
      assertEquals("topic.queue1", binding0.getDestination());
      assertEquals("topicExchage", binding0.getExchange());
      assertEquals("topic.key1", binding0.getRoutingKey());
  }}
