/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.rabbitmq;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.jesper.seckill.rabbitmq.MQReceiver;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MQReceiver_SSTest extends MQReceiver_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_receive_0()  throws Throwable  {
      //caseID:f30eedc1fe52102ca9f284e6c100423d
      MQReceiver mQReceiver0 = new MQReceiver();
      // Undeclared exception!
      try { 

        //invoke method for mQReceiver0
        mQReceiver0.receive("");
      } catch(Throwable e) {
         verifyException("com.jesper.seckill.rabbitmq.MQReceiver", e);
         assertEquals("java.lang.NullPointerException", e.getClass().getName());
      }
  }
  @Test(timeout = 4000)
  public void test_receiveTopic2_1()  throws Throwable  {
      //caseID:5498b95003bf21c3be1000965b6302e4
      MQReceiver mQReceiver0 = new MQReceiver();

      //invoke method for mQReceiver0
      mQReceiver0.receiveTopic2("p[");
  }
  @Test(timeout = 4000)
  public void test_receiveTopic1_2()  throws Throwable  {
      //caseID:9a030ce470414b2ac26e704d607509c8
      MQReceiver mQReceiver0 = new MQReceiver();

      //invoke method for mQReceiver0
      mQReceiver0.receiveTopic1("`5\"@;BTDC!]u*A");
  }}
