/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.rabbitmq;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.jesper.seckill.bean.User;
import com.jesper.seckill.rabbitmq.SeckillMessage;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SeckillMessage_SSTest extends SeckillMessage_SSTest_scaffolding {
// allCoveredLines:[10, 16, 20, 21, 24, 28, 29]

  @Test(timeout = 4000)
  public void test_getGoodsId_0()  throws Throwable  {
      //caseID:223db70cb81ad8b058b5179ac2f34749
      //CoveredLines: [10, 24]
      //Assert: assertEquals(0L, method_result);
      
      SeckillMessage seckillMessage0 = new SeckillMessage();
      
      //Call method: getGoodsId
      long long0 = seckillMessage0.getGoodsId();
      
      //Test Result Assert
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test_getUser_1()  throws Throwable  {
      //caseID:0ad6ffcbd19ec4d9a061e46c64a20373
      //CoveredLines: [10, 16]
      //Assert: assertNull(method_result);
      
      SeckillMessage seckillMessage0 = new SeckillMessage();
      
      //Call method: getUser
      User user0 = seckillMessage0.getUser();
      
      //Test Result Assert
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test_setGoodsId_2()  throws Throwable  {
      //caseID:a2526c1ed22b397854dfd3255c24e45a
      //CoveredLines: [10, 28, 29]
      //Input_0_long: 0L
      
      SeckillMessage seckillMessage0 = new SeckillMessage();
      
      //Call method: setGoodsId
      seckillMessage0.setGoodsId(0L);
      
      //Test Result Assert
      assertEquals(0L, seckillMessage0.getGoodsId());
  }

  @Test(timeout = 4000)
  public void test_setUser_3()  throws Throwable  {
      //caseID:6b7647dc8540a4152601324683df2f01
      //CoveredLines: [10, 20, 21]
      //Input_0_User: {}
      
      SeckillMessage seckillMessage0 = new SeckillMessage();
      //mock user0
      User user0 = mock(User.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: setUser
      seckillMessage0.setUser(user0);
      
      //Test Result Assert
      assertEquals(0L, seckillMessage0.getGoodsId());
  }
}
