/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.limit;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.limit.RateLimiterDemo;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class RateLimiterDemo_SSTest extends RateLimiterDemo_SSTest_scaffolding {
// allCoveredLines:[13]

  @Test(timeout = 4000)
  public void test_setCurrentTimeMillis_0()  throws Throwable  {
      //caseID:a2869d47b5e09f732bbfab8cb828363e
      //CoveredLines: [13]
      
      RateLimiterDemo rateLimiterDemo0 = new RateLimiterDemo();
  }
}
