/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.bean.Goods;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Goods_SSTest extends Goods_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getId_00()  throws Throwable  {
      //caseID:cfc114f6e0635dff94a0997d2a74146d
      Goods goods0 = new Goods();
      Long long0 = goods0.getId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsPrice_01()  throws Throwable  {
      //caseID:75f4e1bb2c7c98e1614ed4538a635c28
      Goods goods0 = new Goods();
      Double double0 = goods0.getGoodsPrice();
      assertNull(double0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsTitle_02()  throws Throwable  {
      //caseID:40623fca7d7066cbc437555e3721fd57
      Goods goods0 = new Goods();
      String string0 = goods0.getGoodsName();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsStock_03()  throws Throwable  {
      //caseID:a4536ae056504242b816435bc48cf0fc
      Goods goods0 = new Goods();
      Integer integer0 = goods0.getGoodsStock();
      assertNull(integer0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsDetail_04()  throws Throwable  {
      //caseID:6e2da4a255239d0d798d390f160dedc3
      Goods goods0 = new Goods();
      String string0 = goods0.getGoodsDetail();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsImg_05()  throws Throwable  {
      //caseID:82c5b5e5d181de17622f4a02f0979346
      Goods goods0 = new Goods();
      String string0 = goods0.getGoodsImg();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsTitle_06()  throws Throwable  {
      //caseID:e562a174b565903db9576f1d64e44fd4
      Goods goods0 = new Goods();
      String string0 = goods0.getGoodsTitle();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_setGoodsStock_07()  throws Throwable  {
      //caseID:20f0f5d821b93234067a84f41650c2af
      Goods goods0 = new Goods();
      Integer integer0 = new Integer((-59));

      //invoke method for goods0
      goods0.setGoodsStock(integer0);

      //invoke method for goods0
      assertNull(goods0.getGoodsPrice());
  }
  @Test(timeout = 4000)
  public void test_setGoodsTitle_08()  throws Throwable  {
      //caseID:149b962876250004bd42d07d7be4d1af
      Goods goods0 = new Goods();

      //invoke method for goods0
      goods0.setGoodsTitle("f3+/0)Xp#q;QOIL%");

      //invoke method for goods0
      assertNull(goods0.getGoodsStock());
  }
  @Test(timeout = 4000)
  public void test_setGoodsDetail_09()  throws Throwable  {
      //caseID:455d6f98f8d2aa876fa9dab4972bc9ec
      Goods goods0 = new Goods();

      //invoke method for goods0
      goods0.setGoodsDetail("");

      //invoke method for goods0
      assertNull(goods0.getGoodsTitle());
  }
  @Test(timeout = 4000)
  public void test_setGoodsPrice_10()  throws Throwable  {
      //caseID:d16dec6c4edb1abae5a1ba325fed627e
      Goods goods0 = new Goods();
      Double double0 = new Double(0.0);

      //invoke method for goods0
      goods0.setGoodsPrice(double0);

      //invoke method for goods0
      assertNull(goods0.getGoodsTitle());
  }
  @Test(timeout = 4000)
  public void test_setGoodsImg_11()  throws Throwable  {
      //caseID:edf8512d45790ec2752e76e23777951d
      Goods goods0 = new Goods();

      //invoke method for goods0
      goods0.setGoodsImg("1.0");

      //invoke method for goods0
      assertNull(goods0.getId());
  }
  @Test(timeout = 4000)
  public void test_setGoodsName_12()  throws Throwable  {
      //caseID:7b0082f8701f95fd802b5b115d4b7fbd
      Goods goods0 = new Goods();

      //invoke method for goods0
      goods0.setGoodsName("1");

      //invoke method for goods0
      assertEquals("1", goods0.getGoodsName());
  }
  @Test(timeout = 4000)
  public void test_setId_13()  throws Throwable  {
      //caseID:631ab2e73758c8e6d8ecbbe3b0e25ed2
      Goods goods0 = new Goods();
      Long long0 = new Long(1);

      //invoke method for goods0
      goods0.setId(long0);

      //invoke method for goods0
      assertEquals(1L, (long)goods0.getId());
  }}
