/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.jesper.seckill.bean.OrderInfo;
import java.util.Date;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OrderInfo_SSTest extends OrderInfo_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_setCreateDate_00()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

      //invoke method for orderInfo0
      orderInfo0.setCreateDate(date0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getId());
  }
  @Test(timeout = 4000)
  public void test_setOrderChannel_01()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      Integer integer0 = new Integer(192);

      //invoke method for orderInfo0
      orderInfo0.setOrderChannel(integer0);

      //invoke method for orderInfo0
      assertEquals(192, (int)orderInfo0.getOrderChannel());
  }
  @Test(timeout = 4000)
  public void test_setId_02()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      Long long0 = new Long(2410L);

      //invoke method for orderInfo0
      orderInfo0.setId(long0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getGoodsCount());
  }
  @Test(timeout = 4000)
  public void test_setStatus_03()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      Integer integer0 = new Integer(1);

      //invoke method for orderInfo0
      orderInfo0.setStatus(integer0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getUserId());
  }
  @Test(timeout = 4000)
  public void test_setGoodsName_04()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.setGoodsName("1");

      //invoke method for orderInfo0
      assertNull(orderInfo0.getGoodsPrice());
  }
  @Test(timeout = 4000)
  public void test_getGoodsName_05()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.getUserId();
      String string0 = orderInfo0.getGoodsName();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getId_06()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.getGoodsPrice();

      //invoke method for orderInfo0
      orderInfo0.getStatus();
      Long long0 = orderInfo0.getDeliveryAddrId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getId_07()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.getGoodsPrice();

      //invoke method for orderInfo0
      orderInfo0.getStatus();
      Long long0 = orderInfo0.getGoodsId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_setGoodsPrice_08()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      Double double0 = new Double((-86.945178004));

      //invoke method for orderInfo0
      orderInfo0.getPayDate();

      //invoke method for orderInfo0
      orderInfo0.setGoodsPrice(double0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getDeliveryAddrId());
  }
  @Test(timeout = 4000)
  public void test_setPayDate_09()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.getGoodsPrice();
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

      //invoke method for orderInfo0
      orderInfo0.setPayDate(date0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getGoodsPrice());
  }
  @Test(timeout = 4000)
  public void test_setDeliveryAddrId_10()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.getOrderChannel();
      Long long0 = new Long(2084L);

      //invoke method for orderInfo0
      orderInfo0.setDeliveryAddrId(long0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getOrderChannel());
  }
  @Test(timeout = 4000)
  public void test_getGoodsCount_11()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.getUserId();

      //invoke method for orderInfo0
      orderInfo0.getCreateDate();
      Integer integer0 = orderInfo0.getGoodsCount();
      assertNull(integer0);
  }
  @Test(timeout = 4000)
  public void test_setGoodsId_12()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.getGoodsId();

      //invoke method for orderInfo0
      orderInfo0.setGoodsId((Long) null);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getGoodsCount());
  }
  @Test(timeout = 4000)
  public void test_setUserId_13()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.getGoodsCount();
      Long long0 = new Long(0L);

      //invoke method for orderInfo0
      orderInfo0.setUserId(long0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getStatus());
  }
  @Test(timeout = 4000)
  public void test_setGoodsCount_14()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();
      Integer integer0 = orderInfo0.getGoodsCount();

      //invoke method for orderInfo0
      orderInfo0.setGoodsCount(integer0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getStatus());
  }
  @Test(timeout = 4000)
  public void test_getId_15()  throws Throwable  {
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.getGoodsPrice();

      //invoke method for orderInfo0
      orderInfo0.getOrderChannel();

      //invoke method for orderInfo0
      orderInfo0.getGoodsId();
      Long long0 = orderInfo0.getId();
      assertNull(long0);
  }}
