/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.jesper.seckill.bean.OrderInfo;
import java.util.Date;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OrderInfo_SSTest extends OrderInfo_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getDeliveryAddrId_00()  throws Throwable  {
      //caseID:194641c1c5fb66b1eccbccef5e7d952c
      OrderInfo orderInfo0 = new OrderInfo();
      Long long0 = orderInfo0.getDeliveryAddrId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getPayDate_01()  throws Throwable  {
      //caseID:49509dd2e35cab89c1f52fe06dea537e
      OrderInfo orderInfo0 = new OrderInfo();
      Date date0 = orderInfo0.getPayDate();
      assertNull(date0);
  }
  @Test(timeout = 4000)
  public void test_getUserId_02()  throws Throwable  {
      //caseID:6c21ea171ac2642a7dd67bc6b93a9b78
      OrderInfo orderInfo0 = new OrderInfo();
      Long long0 = orderInfo0.getUserId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsName_03()  throws Throwable  {
      //caseID:676f33913f2ad28d2ccba185e56e9897
      OrderInfo orderInfo0 = new OrderInfo();
      String string0 = orderInfo0.getGoodsName();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getId_04()  throws Throwable  {
      //caseID:22ddf6b5c0644649dc04f5aa49d22aa3
      OrderInfo orderInfo0 = new OrderInfo();
      Long long0 = orderInfo0.getId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsPrice_05()  throws Throwable  {
      //caseID:bd7df63053468bbc99d6ed6fdbafeab6
      OrderInfo orderInfo0 = new OrderInfo();
      Double double0 = orderInfo0.getGoodsPrice();
      assertNull(double0);
  }
  @Test(timeout = 4000)
  public void test_getStatus_06()  throws Throwable  {
      //caseID:31b04609401ac6961ef5a6a15ebef5d5
      OrderInfo orderInfo0 = new OrderInfo();
      Integer integer0 = orderInfo0.getStatus();
      assertNull(integer0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsId_07()  throws Throwable  {
      //caseID:0bd29218234c5bcfcab40b128cdc63eb
      OrderInfo orderInfo0 = new OrderInfo();
      Long long0 = orderInfo0.getGoodsId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getOrderChannel_08()  throws Throwable  {
      //caseID:17091bdd9ed0cf65be617da99166a911
      OrderInfo orderInfo0 = new OrderInfo();
      Integer integer0 = orderInfo0.getOrderChannel();
      assertNull(integer0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsCount_09()  throws Throwable  {
      //caseID:87af25ed7a64db7b0dc273d0e9264284
      OrderInfo orderInfo0 = new OrderInfo();
      Integer integer0 = orderInfo0.getGoodsCount();
      assertNull(integer0);
  }
  @Test(timeout = 4000)
  public void test_getPayDate_10()  throws Throwable  {
      //caseID:4bfb2d1665b4df42ee56eec810b04def
      OrderInfo orderInfo0 = new OrderInfo();
      Date date0 = orderInfo0.getCreateDate();
      assertNull(date0);
  }
  @Test(timeout = 4000)
  public void test_setUserId_11()  throws Throwable  {
      //caseID:b20012b70869958daef7232a7656c264
      OrderInfo orderInfo0 = new OrderInfo();
      Long long0 = new Long((-16));

      //invoke method for orderInfo0
      orderInfo0.setUserId(long0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getId());
  }
  @Test(timeout = 4000)
  public void test_setGoodsName_12()  throws Throwable  {
      //caseID:2fa7ab2e7164cb8404d4b4f8e41114a9
      OrderInfo orderInfo0 = new OrderInfo();

      //invoke method for orderInfo0
      orderInfo0.setGoodsName("57343");

      //invoke method for orderInfo0
      assertNull(orderInfo0.getUserId());
  }
  @Test(timeout = 4000)
  public void test_setPayDate_13()  throws Throwable  {
      //caseID:ec4c4647e4315378115eeb31737d7110
      OrderInfo orderInfo0 = new OrderInfo();
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

      //invoke method for orderInfo0
      orderInfo0.setPayDate(date0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getOrderChannel());
  }
  @Test(timeout = 4000)
  public void test_setGoodsCount_14()  throws Throwable  {
      //caseID:4ea5acff976ce80c645442dd3471af02
      OrderInfo orderInfo0 = new OrderInfo();
      Integer integer0 = new Integer(2003);

      //invoke method for orderInfo0
      orderInfo0.setGoodsCount(integer0);

      //invoke method for orderInfo0
      assertEquals(2003, (int)orderInfo0.getGoodsCount());
  }
  @Test(timeout = 4000)
  public void test_setGoodsPrice_15()  throws Throwable  {
      //caseID:e4001a3c6881d0982beb28fb64b98c27
      OrderInfo orderInfo0 = new OrderInfo();
      Double double0 = new Double(0.0);

      //invoke method for orderInfo0
      orderInfo0.setGoodsPrice(double0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getUserId());
  }
  @Test(timeout = 4000)
  public void test_setCreateDate_16()  throws Throwable  {
      //caseID:f5ee8fef3b310661f4dd0e9d91bdfd53
      OrderInfo orderInfo0 = new OrderInfo();
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

      //invoke method for orderInfo0
      orderInfo0.setCreateDate(date0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getGoodsPrice());
  }
  @Test(timeout = 4000)
  public void test_setId_17()  throws Throwable  {
      //caseID:27dad1f8d2efeb2312a1c0247574d382
      OrderInfo orderInfo0 = new OrderInfo();
      Long long0 = new Long(0);

      //invoke method for orderInfo0
      orderInfo0.setId(long0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getOrderChannel());
  }
  @Test(timeout = 4000)
  public void test_setStatus_18()  throws Throwable  {
      //caseID:9ef25f79e27fcf370f3328590f6ddf58
      OrderInfo orderInfo0 = new OrderInfo();
      Integer integer0 = new Integer(1);

      //invoke method for orderInfo0
      orderInfo0.setStatus(integer0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getOrderChannel());
  }
  @Test(timeout = 4000)
  public void test_setOrderChannel_19()  throws Throwable  {
      //caseID:8d6899720ca1c7f7881b8b70498b88f9
      OrderInfo orderInfo0 = new OrderInfo();
      Integer integer0 = new Integer((-1));

      //invoke method for orderInfo0
      orderInfo0.setOrderChannel(integer0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getGoodsId());
  }
  @Test(timeout = 4000)
  public void test_setGoodsId_20()  throws Throwable  {
      //caseID:a04f1b94c1954d3a4f1fe59865e85b57
      OrderInfo orderInfo0 = new OrderInfo();
      Long long0 = new Long(18);

      //invoke method for orderInfo0
      orderInfo0.setGoodsId(long0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getId());
  }
  @Test(timeout = 4000)
  public void test_setDeliveryAddrId_21()  throws Throwable  {
      //caseID:dbc8914d2785bd24dac3a115caac3a55
      OrderInfo orderInfo0 = new OrderInfo();
      Long long0 = new Long(1886);

      //invoke method for orderInfo0
      orderInfo0.setDeliveryAddrId(long0);

      //invoke method for orderInfo0
      assertNull(orderInfo0.getGoodsName());
  }}
