/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.bean.SeckillOrder;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SeckillOrder_SSTest extends SeckillOrder_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_setUserId_0()  throws Throwable  {
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(1L);

      //invoke method for seckillOrder0
      seckillOrder0.setUserId(long0);

      //invoke method for seckillOrder0
      assertEquals(1L, (long)seckillOrder0.getUserId());
  }
  @Test(timeout = 4000)
  public void test_setGoodsId_1()  throws Throwable  {
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(0L);

      //invoke method for seckillOrder0
      seckillOrder0.setGoodsId(long0);

      //invoke method for seckillOrder0
      assertEquals(0L, (long)seckillOrder0.getGoodsId());
  }
  @Test(timeout = 4000)
  public void test_getOrderId_2()  throws Throwable  {
      SeckillOrder seckillOrder0 = new SeckillOrder();

      //invoke method for seckillOrder0
      seckillOrder0.getOrderId();
      Long long0 = seckillOrder0.getGoodsId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_setId_3()  throws Throwable  {
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(3564L);

      //invoke method for seckillOrder0
      seckillOrder0.getUserId();

      //invoke method for seckillOrder0
      seckillOrder0.setId(long0);

      //invoke method for seckillOrder0
      assertEquals(3564L, (long)seckillOrder0.getId());
  }
  @Test(timeout = 4000)
  public void test_setOrderId_4()  throws Throwable  {
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(229L);

      //invoke method for seckillOrder0
      seckillOrder0.getGoodsId();

      //invoke method for seckillOrder0
      seckillOrder0.setOrderId(long0);

      //invoke method for seckillOrder0
      assertNull(seckillOrder0.getId());
  }
  @Test(timeout = 4000)
  public void test_setId_5()  throws Throwable  {
      SeckillOrder seckillOrder0 = new SeckillOrder();

      //invoke method for seckillOrder0
      seckillOrder0.getId();

      //invoke method for seckillOrder0
      seckillOrder0.setId((Long) null);

      //invoke method for seckillOrder0
      assertNull(seckillOrder0.getUserId());
  }}
