/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.bean.SeckillOrder;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SeckillOrder_SSTest extends SeckillOrder_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getUserId_0()  throws Throwable  {
      //caseID:557b43cb863abe203f6d570f0e4bb522
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = seckillOrder0.getUserId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsId_1()  throws Throwable  {
      //caseID:cea3dece93efe7c9419d1998de409f95
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = seckillOrder0.getGoodsId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getOrderId_2()  throws Throwable  {
      //caseID:6fd3ec2225c6688acb277b87bea8f0a0
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = seckillOrder0.getOrderId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getId_3()  throws Throwable  {
      //caseID:59e1a840649c7d66a97a01f7f6538ea9
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = seckillOrder0.getId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_setId_4()  throws Throwable  {
      //caseID:fbd103979ff4b78a93e7fa928567c065
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(0L);

      //invoke method for seckillOrder0
      seckillOrder0.setId(long0);

      //invoke method for seckillOrder0
      assertEquals(0L, (long)seckillOrder0.getId());
  }
  @Test(timeout = 4000)
  public void test_setUserId_5()  throws Throwable  {
      //caseID:47134cb048d19b608fc4db87b28be67a
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(1302L);

      //invoke method for seckillOrder0
      seckillOrder0.setUserId(long0);

      //invoke method for seckillOrder0
      assertNull(seckillOrder0.getGoodsId());
  }
  @Test(timeout = 4000)
  public void test_setOrderId_6()  throws Throwable  {
      //caseID:3e279170382d75f842d9a3ca99c71768
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(48L);

      //invoke method for seckillOrder0
      seckillOrder0.setOrderId(long0);

      //invoke method for seckillOrder0
      assertEquals(48L, (long)seckillOrder0.getOrderId());
  }
  @Test(timeout = 4000)
  public void test_setGoodsId_7()  throws Throwable  {
      //caseID:48d155f9667d1c96a2d30650a4bf7c17
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(0L);

      //invoke method for seckillOrder0
      seckillOrder0.setGoodsId(long0);

      //invoke method for seckillOrder0
      assertNull(seckillOrder0.getUserId());
  }}
