/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.bean.SeckillOrder;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SeckillOrder_SSTest extends SeckillOrder_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getUserId_0()  throws Throwable  {
      //caseID:46688f3592ac7f0594874c1216070891
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = seckillOrder0.getUserId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsId_1()  throws Throwable  {
      //caseID:3ffa10c9aec4c55032f287325fa5c906
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = seckillOrder0.getGoodsId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getId_2()  throws Throwable  {
      //caseID:d876ef28e6fea25340cd90db9186f12c
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = seckillOrder0.getId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getOrderId_3()  throws Throwable  {
      //caseID:c687899f7257ac12754253cea2503e4d
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = seckillOrder0.getOrderId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_setId_4()  throws Throwable  {
      //caseID:b764b2d53e3eb49e667418f82b646098
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(3294L);

      //invoke method for seckillOrder0
      seckillOrder0.setId(long0);

      //invoke method for seckillOrder0
      assertNull(seckillOrder0.getGoodsId());
  }
  @Test(timeout = 4000)
  public void test_setUserId_5()  throws Throwable  {
      //caseID:47d09400a9102933505e8556b35bae42
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(0L);

      //invoke method for seckillOrder0
      seckillOrder0.setUserId(long0);

      //invoke method for seckillOrder0
      assertNull(seckillOrder0.getId());
  }
  @Test(timeout = 4000)
  public void test_setOrderId_6()  throws Throwable  {
      //caseID:293f8b79239e5dffb8e57f5226451a27
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(0L);

      //invoke method for seckillOrder0
      seckillOrder0.setOrderId(long0);

      //invoke method for seckillOrder0
      assertEquals(0L, (long)seckillOrder0.getOrderId());
  }
  @Test(timeout = 4000)
  public void test_setGoodsId_7()  throws Throwable  {
      //caseID:5e7d06d80fd1b32109b67ea52c8e9e2c
      SeckillOrder seckillOrder0 = new SeckillOrder();
      Long long0 = new Long(0L);

      //invoke method for seckillOrder0
      seckillOrder0.setGoodsId(long0);

      //invoke method for seckillOrder0
      assertNull(seckillOrder0.getOrderId());
  }}
