/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.bean;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.jesper.seckill.bean.SeckillGoods;
import java.util.Date;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SeckillGoods_SSTest extends SeckillGoods_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getStartDate_00()  throws Throwable  {
      //caseID:56641c692eb941481e238940c748cc7b
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Date date0 = seckillGoods0.getStartDate();
      assertNull(date0);
  }
  @Test(timeout = 4000)
  public void test_getStockCount_01()  throws Throwable  {
      //caseID:25a331050b51d62afaa5b444d74d100c
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Integer integer0 = seckillGoods0.getStockCount();
      assertNull(integer0);
  }
  @Test(timeout = 4000)
  public void test_getStartDate_02()  throws Throwable  {
      //caseID:644deb38e157350125d9a0fdd0b0def5
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Date date0 = seckillGoods0.getEndDate();
      assertNull(date0);
  }
  @Test(timeout = 4000)
  public void test_getId_03()  throws Throwable  {
      //caseID:4a7f1fed62dc615117fafbfe46297c9d
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Long long0 = seckillGoods0.getId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getGoodsId_04()  throws Throwable  {
      //caseID:a4c4ad4bd335e72c324710152eeb2fd1
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Long long0 = seckillGoods0.getGoodsId();
      assertNull(long0);
  }
  @Test(timeout = 4000)
  public void test_getVersion_05()  throws Throwable  {
      //caseID:90f88b3e5e4c101c1772d39e0d856f2d
      SeckillGoods seckillGoods0 = new SeckillGoods();
      int int0 = seckillGoods0.getVersion();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_setStartDate_06()  throws Throwable  {
      //caseID:da9c68dd1031585bc3a37e7958ef00fd
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

      //invoke method for seckillGoods0
      seckillGoods0.setStartDate(date0);

      //invoke method for seckillGoods0
      assertEquals(0, seckillGoods0.getVersion());
  }
  @Test(timeout = 4000)
  public void test_setGoodsId_07()  throws Throwable  {
      //caseID:36eaaf0c478b09ade5969b1d1eecb1bf
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Long long0 = new Long(6);

      //invoke method for seckillGoods0
      seckillGoods0.setGoodsId(long0);

      //invoke method for seckillGoods0
      assertNull(seckillGoods0.getStockCount());
  }
  @Test(timeout = 4000)
  public void test_setEndDate_08()  throws Throwable  {
      //caseID:15279c0225f4799a6dd5bac614ae62f1
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Date date0 = mock(Date.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());

      //invoke method for seckillGoods0
      seckillGoods0.setEndDate(date0);

      //invoke method for seckillGoods0
      assertNull(seckillGoods0.getStockCount());
  }
  @Test(timeout = 4000)
  public void test_setStockCount_09()  throws Throwable  {
      //caseID:b9b5e55b4f5256bac4925982746ff7be
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Integer integer0 = new Integer(13);

      //invoke method for seckillGoods0
      seckillGoods0.setStockCount(integer0);

      //invoke method for seckillGoods0
      assertNull(seckillGoods0.getId());
  }
  @Test(timeout = 4000)
  public void test_setVersion_10()  throws Throwable  {
      //caseID:4262fca88166677db2966898d01777d1
      SeckillGoods seckillGoods0 = new SeckillGoods();

      //invoke method for seckillGoods0
      seckillGoods0.setVersion(5);

      //invoke method for seckillGoods0
      assertEquals(5, seckillGoods0.getVersion());
  }
  @Test(timeout = 4000)
  public void test_setId_11()  throws Throwable  {
      //caseID:7e7b33332c9b414fb9f42cba2870d8a4
      SeckillGoods seckillGoods0 = new SeckillGoods();
      Long long0 = new Long(55303);

      //invoke method for seckillGoods0
      seckillGoods0.setId(long0);

      //invoke method for seckillGoods0
      assertEquals(0, seckillGoods0.getVersion());
  }}
