/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.redis;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.redis.OrderKey;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OrderKey_SSTest extends OrderKey_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      //caseID:d2d00d6f6ada52688f36f7c21cdbf1d9
      OrderKey orderKey0 = new OrderKey("");

      //invoke method for orderKey0
      assertEquals(0, orderKey0.expireSeconds());
  }}
