/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.redis;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.redis.RedisConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class RedisConfig_SSTest extends RedisConfig_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getHost_00()  throws Throwable  {
      //caseID:cfc35806f021084162e905ca3b9f7df1
      RedisConfig redisConfig0 = new RedisConfig();
      String string0 = redisConfig0.getHost();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getPoolMaxWait_01()  throws Throwable  {
      //caseID:4572bc9bc0e207a5bdad3b1504b49645
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPoolMaxWait();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getTimeout_02()  throws Throwable  {
      //caseID:0e489d83a59e0e3cfd64ae9061478a02
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getTimeout();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPoolMaxTotal_03()  throws Throwable  {
      //caseID:0ca2302eeaa720ef774d58b6b2309bb6
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPoolMaxTotal();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPort_04()  throws Throwable  {
      //caseID:f1510fea4ed8220113f62acc04fffe5a
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPort();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPoolMaxIdle_05()  throws Throwable  {
      //caseID:00faf4c885fd210344d5c5e3dd6aa2c7
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPoolMaxIdle();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPassword_06()  throws Throwable  {
      //caseID:d3a9378a2777231c77f0adf63053876a
      RedisConfig redisConfig0 = new RedisConfig();
      String string0 = redisConfig0.getPassword();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_setPoolMaxWait_07()  throws Throwable  {
      //caseID:a4ad79ef02affdb6f5432b880c5908f8
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPoolMaxWait(1);

      //invoke method for redisConfig0
      assertEquals(1, redisConfig0.getPoolMaxWait());
  }
  @Test(timeout = 4000)
  public void test_setPassword_08()  throws Throwable  {
      //caseID:ff6cf7e6da19e6929c5c0a65df7f09aa
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPassword("1");

      //invoke method for redisConfig0
      assertEquals(0, redisConfig0.getPoolMaxTotal());
  }
  @Test(timeout = 4000)
  public void test_setTimeout_09()  throws Throwable  {
      //caseID:6f72bde354ea481d1f7a53d5355a32b1
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setTimeout(0);

      //invoke method for redisConfig0
      assertEquals(0, redisConfig0.getTimeout());
  }
  @Test(timeout = 4000)
  public void test_setHost_10()  throws Throwable  {
      //caseID:80838dece9882ddd1437b1a6f02c8b2c
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setHost("");

      //invoke method for redisConfig0
      assertEquals(0, redisConfig0.getPoolMaxWait());
  }
  @Test(timeout = 4000)
  public void test_setPoolMaxTotal_11()  throws Throwable  {
      //caseID:e99a2887ba3e6f40c0a8afb6742bfb59
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPoolMaxTotal((-1));

      //invoke method for redisConfig0
      assertEquals((-1), redisConfig0.getPoolMaxTotal());
  }
  @Test(timeout = 4000)
  public void test_setPort_12()  throws Throwable  {
      //caseID:280812e81a641e4fd6432e61c5a7cbf2
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPort((-1));

      //invoke method for redisConfig0
      assertEquals((-1), redisConfig0.getPort());
  }
  @Test(timeout = 4000)
  public void test_setPoolMaxIdle_13()  throws Throwable  {
      //caseID:74a4434621ddf45828e641d2b960c24c
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPoolMaxIdle(1);

      //invoke method for redisConfig0
      assertEquals(1, redisConfig0.getPoolMaxIdle());
  }}
