/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.redis;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.jesper.seckill.redis.RedisConfig;
import com.jesper.seckill.redis.RedisPoolFactory;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;
import redis.clients.jedis.JedisPool;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class RedisPoolFactory_SSTest extends RedisPoolFactory_SSTest_scaffolding {
// allCoveredLines:[10, 21, 22, 23, 24, 25, 26, 27]

  @Test(timeout = 4000)
  public void test_JedisPoolFactory_0()  throws Throwable  {
      //caseID:2e434791388fa4ddfeeb6c4467101143
      //CoveredLines: [10, 21, 22, 23, 24, 25, 26, 27]
      //Assert: assertEquals(0L, method_result.getMeanBorrowWaitTimeMillis());
      
      RedisPoolFactory redisPoolFactory0 = new RedisPoolFactory();
      //mock redisConfig0
      RedisConfig redisConfig0 = mock(RedisConfig.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      PrivateAccess.setVariable((Class<?>) RedisPoolFactory.class, redisPoolFactory0, "redisConfig", (Object) redisConfig0);
      
      //Call method: JedisPoolFactory
      JedisPool jedisPool0 = redisPoolFactory0.JedisPoolFactory();
      
      //Test Result Assert
      assertEquals(0L, jedisPool0.getMeanBorrowWaitTimeMillis());
  }
}
