/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.redis;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.redis.RedisConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class RedisConfig_SSTest extends RedisConfig_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getPoolMaxTotal_00()  throws Throwable  {
      //caseID:d97b412f4ed882c43e28da5221e4b9e0
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPoolMaxTotal();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPassword_01()  throws Throwable  {
      //caseID:0b41ea5ed88a16309b7a41b371df5b9b
      RedisConfig redisConfig0 = new RedisConfig();
      String string0 = redisConfig0.getPassword();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getPoolMaxWait_02()  throws Throwable  {
      //caseID:0de889d6783e13d59d07bb9884e45b84
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPoolMaxWait();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getTimeout_03()  throws Throwable  {
      //caseID:eaf543825c7cfd7d27d1bfba1e3b26f2
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getTimeout();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPoolMaxIdle_04()  throws Throwable  {
      //caseID:b7215f98671ca0c89a73d4511cb412e1
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPoolMaxIdle();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPort_05()  throws Throwable  {
      //caseID:30156d0bbfe8e4aacf405a1e3bcfb3d4
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPort();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getHost_06()  throws Throwable  {
      //caseID:10529dc3db553965e3eda4c23f3cfeb6
      RedisConfig redisConfig0 = new RedisConfig();
      String string0 = redisConfig0.getHost();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_setPort_07()  throws Throwable  {
      //caseID:31affed7caa517b704ced624e6067215
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPort(1077);

      //invoke method for redisConfig0
      assertEquals(1077, redisConfig0.getPort());
  }
  @Test(timeout = 4000)
  public void test_setPoolMaxTotal_08()  throws Throwable  {
      //caseID:c92435642bc6e181bbe357b101028e23
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPoolMaxTotal(1729);

      //invoke method for redisConfig0
      assertEquals(1729, redisConfig0.getPoolMaxTotal());
  }
  @Test(timeout = 4000)
  public void test_setPoolMaxWait_09()  throws Throwable  {
      //caseID:725039943f37bbd6dcf4faa4cdff7871
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPoolMaxWait(0);

      //invoke method for redisConfig0
      assertEquals(0, redisConfig0.getPoolMaxWait());
  }
  @Test(timeout = 4000)
  public void test_setPassword_10()  throws Throwable  {
      //caseID:6df6f14aa423695b8c9f8162eb7e9fe7
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPassword("com.jesper.seckill.redis.RedisConfig");

      //invoke method for redisConfig0
      assertEquals(0, redisConfig0.getPoolMaxWait());
  }
  @Test(timeout = 4000)
  public void test_setTimeout_11()  throws Throwable  {
      //caseID:b754b652e9175dafed7aa099ede4e81e
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setTimeout(0);

      //invoke method for redisConfig0
      assertEquals(0, redisConfig0.getTimeout());
  }
  @Test(timeout = 4000)
  public void test_setPoolMaxIdle_12()  throws Throwable  {
      //caseID:247e1da08415554858c0b261efe97d8b
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPoolMaxIdle(2577);

      //invoke method for redisConfig0
      assertEquals(2577, redisConfig0.getPoolMaxIdle());
  }
  @Test(timeout = 4000)
  public void test_setHost_13()  throws Throwable  {
      //caseID:081c0de0939639817afd9b41e7073b23
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setHost("1");

      //invoke method for redisConfig0
      assertEquals(0, redisConfig0.getPoolMaxWait());
  }}
