/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.redis;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.redis.RedisConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class RedisConfig_SSTest extends RedisConfig_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getPoolMaxWait_00()  throws Throwable  {
      //caseID:c3d18b1588baeb08147e176c2a1cca9f
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPoolMaxWait();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPoolMaxTotal_01()  throws Throwable  {
      //caseID:4bdfead2ff813f9ed43315c9d0e46c97
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPoolMaxTotal();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPoolMaxIdle_02()  throws Throwable  {
      //caseID:c140d9a090adffe5d9f2041cf8ecf915
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPoolMaxIdle();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getHost_03()  throws Throwable  {
      //caseID:2b9e40b1f6c8b55a82314df5453e834e
      RedisConfig redisConfig0 = new RedisConfig();
      String string0 = redisConfig0.getHost();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getPassword_04()  throws Throwable  {
      //caseID:21d67fcf8fa4eb59ecc6c20a3e68b179
      RedisConfig redisConfig0 = new RedisConfig();
      String string0 = redisConfig0.getPassword();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getTimeout_05()  throws Throwable  {
      //caseID:22e819d0aa381eaa5088c613fd2a7424
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getTimeout();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_getPort_06()  throws Throwable  {
      //caseID:323c15a149f61aef0d188cc1feb043ec
      RedisConfig redisConfig0 = new RedisConfig();
      int int0 = redisConfig0.getPort();
      assertEquals(0, int0);
  }
  @Test(timeout = 4000)
  public void test_setPoolMaxIdle_07()  throws Throwable  {
      //caseID:e805f8c4fa5060bd86e525d186cf8b6c
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPoolMaxIdle(1);

      //invoke method for redisConfig0
      assertEquals(1, redisConfig0.getPoolMaxIdle());
  }
  @Test(timeout = 4000)
  public void test_setTimeout_08()  throws Throwable  {
      //caseID:8f54d84a092acffbdb0cb77ddeb61e1d
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setTimeout(986);

      //invoke method for redisConfig0
      assertEquals(986, redisConfig0.getTimeout());
  }
  @Test(timeout = 4000)
  public void test_setPassword_09()  throws Throwable  {
      //caseID:40f95001d0b2ff91daf732ae7da2742a
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPassword("com.jesper.seckill.redis.RedisConfig");

      //invoke method for redisConfig0
      assertEquals("com.jesper.seckill.redis.RedisConfig", redisConfig0.getPassword());
  }
  @Test(timeout = 4000)
  public void test_setPoolMaxWait_10()  throws Throwable  {
      //caseID:1ea5fbbbc30e51116b02c58a8980996f
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPoolMaxWait((-28));

      //invoke method for redisConfig0
      assertEquals((-28), redisConfig0.getPoolMaxWait());
  }
  @Test(timeout = 4000)
  public void test_setHost_11()  throws Throwable  {
      //caseID:6cba989016c8d88a0fc5c42f3860463f
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setHost("1.0");

      //invoke method for redisConfig0
      assertEquals(0, redisConfig0.getPoolMaxTotal());
  }
  @Test(timeout = 4000)
  public void test_setPoolMaxTotal_12()  throws Throwable  {
      //caseID:337542c4b60c89b7b89575119be29e9e
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPoolMaxTotal(2804);

      //invoke method for redisConfig0
      assertEquals(2804, redisConfig0.getPoolMaxTotal());
  }
  @Test(timeout = 4000)
  public void test_setPort_13()  throws Throwable  {
      //caseID:83cbc3dbd4d3903c938911f414147e11
      RedisConfig redisConfig0 = new RedisConfig();

      //invoke method for redisConfig0
      redisConfig0.setPort(101);

      //invoke method for redisConfig0
      assertEquals(101, redisConfig0.getPort());
  }}
