/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.jesper.seckill.util.DBUtil;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DBUtil_SSTest extends DBUtil_SSTest_scaffolding {
// allCoveredLines:[8, 24, 25, 26, 27, 28, 29]

  @Test(timeout = 4000)
  public void test_getConn_0()  throws Throwable  {
      //caseID:9a280e14712c77c4f21672faa008f53d
      //CoveredLines: [8, 24, 25, 26, 27, 28, 29]
      
      DBUtil dBUtil0 = new DBUtil();
      
      //Call method: getConn
      try { 
        DBUtil.getConn();
      } catch(Throwable e) {
         assertEquals("com.mysql.jdbc.exceptions.jdbc4.CommunicationsException", e.getClass().getName());
         assertEquals("Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.", e.getMessage());
      }
  }
}
