/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.util.MD5Util;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MD5Util_SSTest extends MD5Util_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_inputPassToFormPass_0()  throws Throwable  {
      //caseID:f1af91f8ec06ccfcd1c577911aef27ca
      MD5Util mD5Util0 = new MD5Util();
      String string0 = MD5Util.inputPassToFormPass("!erpXn)le");
      assertEquals("204a85285f37c586a948e61b64ec8950", string0);
  }
  @Test(timeout = 4000)
  public void test_main_1()  throws Throwable  {
      //caseID:66549178f926ba0df5adf74d28795678
      String[] stringArray0 = new String[0];
      MD5Util.main(stringArray0);
      assertEquals(0, stringArray0.length);
  }}
