/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.util.MD5Util;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MD5Util_SSTest extends MD5Util_SSTest_scaffolding {
// allCoveredLines:[8, 11, 23, 24, 34, 35, 40, 41, 42, 46, 48]

  @Test(timeout = 4000)
  public void test_main_0()  throws Throwable  {
      //caseID:b7b2f591c8631f4e73581d09d4a54611
      //CoveredLines: [11, 23, 24, 34, 35, 40, 41, 42, 46, 48]
      //Input_0_String[]: stringArray0
      
      String[] stringArray0 = new String[2];
      
      //Call method: main
      MD5Util.main(stringArray0);
      
      //Test Result Assert
      assertEquals(2, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test_md5_1()  throws Throwable  {
      //caseID:967cddade7083dd249944154ce1d49cc
      //CoveredLines: [8, 11]
      //Input_0_String: "\"xy(mN[:2"
      //Assert: assertEquals("807b2d2e932a6f598410f579e4246c1e", method_result);
      
      MD5Util mD5Util0 = new MD5Util();
      
      //Call method: md5
      String string0 = MD5Util.md5("\"xy(mN[:2");
      
      //Test Result Assert
      assertEquals("807b2d2e932a6f598410f579e4246c1e", string0);
  }
}
