/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.jesper.seckill.util.UserUtil;
import com.mysql.jdbc.exceptions.jdbc4.CommunicationsException;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class UserUtil_SSTest extends UserUtil_SSTest_scaffolding {
// allCoveredLines:[21, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 38, 100]

  @Test(timeout = 4000)
  public void test_main_0()  throws Throwable  {
      //caseID:7794b5aef6236605b8299f957501da8f
      //CoveredLines: [21, 24, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 38, 100]
      //Input_0_String[]: stringArray0
      
      UserUtil userUtil0 = new UserUtil();
      String[] stringArray0 = new String[8];
      
      //Call method: main
      try { 
        UserUtil.main(stringArray0);
      } catch(Throwable e) {
         assertEquals("com.mysql.jdbc.exceptions.jdbc4.CommunicationsException", e.getClass().getName());
         assertEquals("Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.", e.getMessage());
      }
  }
}
