/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.util.ValidatorUtil;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ValidatorUtil_SSTest extends ValidatorUtil_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_isMobile_0()  throws Throwable  {
      //caseID:a311cdff0c90ed8f53abf15d4ca3fd97
      ValidatorUtil validatorUtil0 = new ValidatorUtil();
      boolean boolean0 = ValidatorUtil.isMobile("");
      assertFalse(boolean0);
  }
  @Test(timeout = 4000)
  public void test_isMobile_1()  throws Throwable  {
      //caseID:188efe1598f9fc8f3e7eac3c76178333
      ValidatorUtil validatorUtil0 = new ValidatorUtil();
      boolean boolean0 = ValidatorUtil.isMobile("1.0");
      assertFalse(boolean0);
  }}
