/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.jesper.seckill.MainApplication;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MainApplication_SSTest extends MainApplication_SSTest_scaffolding {
// allCoveredLines:[7]

  @Test(timeout = 4000)
  public void test_setCurrentTimeMillis_0()  throws Throwable  {
      //caseID:513aa3fa9f0fda0a934ba1f841920fa7
      //CoveredLines: [7]
      
      MainApplication mainApplication0 = new MainApplication();
  }
}
