/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.jesper.seckill.exception.GlobalException;
import com.jesper.seckill.result.CodeMsg;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class GlobalException_SSTest extends GlobalException_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getCodeMsg_0()  throws Throwable  {
      //caseID:ddc4343bb72a85d4982041d64b9e66db

      //prepare data for codeMsg0
      CodeMsg codeMsg0 = mock(CodeMsg.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("\u5546\u54C1\u5DF2\u7ECF\u79D2\u6740\u5B8C\u6BD5").when(codeMsg0).toString();
      GlobalException globalException0 = new GlobalException(codeMsg0);
      CodeMsg codeMsg1 = globalException0.getCodeMsg();
      assertEquals(0, codeMsg1.getCode());
  }}
