/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.jesper.seckill.service;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.jesper.seckill.bean.OrderInfo;
import com.jesper.seckill.bean.SeckillOrder;
import com.jesper.seckill.bean.User;
import com.jesper.seckill.mapper.OrderMapper;
import com.jesper.seckill.redis.RedisService;
import com.jesper.seckill.service.OrderService;
import com.jesper.seckill.vo.GoodsVo;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OrderService_SSTest extends OrderService_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getOrderByUserIdGoodsId_0()  throws Throwable  {
      //caseID:ddc5f19cfc541609d7b960ef2a134946
      OrderService orderService0 = new OrderService();

      //prepare data for redisService0
      SeckillOrder seckillOrder0 = mock(SeckillOrder.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      RedisService redisService0 = mock(RedisService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(seckillOrder0).when(redisService0).get(any(com.jesper.seckill.redis.KeyPrefix.class) , anyString() , any(java.lang.Class.class));

      //invoke method for orderService0
      PrivateAccess.setVariable((Class<?>) OrderService.class, orderService0, "redisService", (Object) redisService0);
      SeckillOrder seckillOrder1 = orderService0.getOrderByUserIdGoodsId(1857L, 0L);
      assertNull(seckillOrder1.getUserId());
  }
  @Test(timeout = 4000)
  public void test_getOrderById_1()  throws Throwable  {
      //caseID:badb7d56ff036d7b14920ac2fa8063a1
      OrderService orderService0 = new OrderService();

      //prepare data for orderMapper0
      OrderInfo orderInfo0 = mock(OrderInfo.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      OrderMapper orderMapper0 = mock(OrderMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(orderInfo0).when(orderMapper0).getOrderById(anyLong());

      //invoke method for orderService0
      PrivateAccess.setVariable((Class<?>) OrderService.class, orderService0, "orderMapper", (Object) orderMapper0);
      OrderInfo orderInfo1 = orderService0.getOrderById(2787L);
      assertNull(orderInfo1.getGoodsPrice());
  }
  @Test(timeout = 4000)
  public void test_createOrder_2()  throws Throwable  {
      //caseID:e9c2bc4dbde36e9a4325f821894d127f
      OrderService orderService0 = new OrderService();

      //prepare data for orderMapper0
      OrderMapper orderMapper0 = mock(OrderMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(39L).when(orderMapper0).insert(any(com.jesper.seckill.bean.OrderInfo.class));
      doReturn((-1)).when(orderMapper0).insertSeckillOrder(any(com.jesper.seckill.bean.SeckillOrder.class));

      //prepare data for redisService0
      Boolean boolean0 = new Boolean("");
      RedisService redisService0 = mock(RedisService.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(boolean0).when(redisService0).set(any(com.jesper.seckill.redis.KeyPrefix.class) , anyString() , any());

      //invoke method for orderService0
      PrivateAccess.setVariable((Class<?>) OrderService.class, orderService0, "redisService", (Object) redisService0);

      //invoke method for orderService0
      PrivateAccess.setVariable((Class<?>) OrderService.class, orderService0, "orderMapper", (Object) orderMapper0);

      //prepare data for goodsVo0
      Long long0 = new Long(860L);
      User user0 = mock(User.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(long0, long0, long0).when(user0).getId();
      Double double0 = new Double(1817.2565084);
      GoodsVo goodsVo0 = mock(GoodsVo.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn("com.jesper.seckill.service.OrderService").when(goodsVo0).getGoodsName();
      doReturn(double0).when(goodsVo0).getGoodsPrice();
      doReturn(long0, long0, long0).when(goodsVo0).getId();
      OrderInfo orderInfo0 = orderService0.createOrder(user0, goodsVo0);
      assertEquals(1, (int)orderInfo0.getGoodsCount());
      assertEquals(0, (int)orderInfo0.getStatus());
      assertEquals(1, (int)orderInfo0.getOrderChannel());
      assertEquals(0L, (long)orderInfo0.getDeliveryAddrId());
  }}
